# Demonstration of Geometric Algebra of the Plane. i.e. generated by Euclidean 2D.
from e2ga import *

def explain(m):
    print str(m) + " is " + repr(m)
    return m

def showValue(name, x):
    print name + " => " + str(x)
    return x

zero = explain(Euclidean2(0,0,0,0))
one  = explain(ScalarE2(1))
two  = explain(ScalarE2(2))
three= explain(ScalarE2(3))
i    = explain(VectorE2(1, 0))
j    = explain(VectorE2(0, 1))
I    = explain(PseudoscalarE2(1))

blades = [zero, one, two, three, i, j, I]

print ""
print "Sum"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " + " + str(b), str(a + b))
print ""
print "Difference"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " - " + str(b), str(a - b))
print ""
print "Geometric Product"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " * " + str(b), str(a * b))
print ""
print "Exterior Product"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " ^ " + str(b), str(a ^ b))
print ""
print "Left Contraction"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " << " + str(b), str(a << b))
print ""
print "Right Contraction"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " >> " + str(b), str(a >> b))
print ""
print "Scalar Product"
for a in blades:
    print ""
    for b in blades:
        showValue(str(a) + " % " + str(b), str(a % b))
