# blade is a Python module for Geometry Zen that contains the algebraic aspect of
# several Geometric Algebras. It currently supports the Geometric Algebra of the Plane and
# the Geometric Algebra generated by a Euclidean 3D vector space.
#
# blade does not support graphics. For that you should use the eight module, which contains an
# encapsulation of the powerful Three.js WebGL API with extensions for Geometric Algebra. The
# eight module also contains its own multivector that is more suited to graphics. 
