# 'blade' is a Python module for Geometry Zen that contains the algebraic aspect of
# several Geometric Algebras. It currently supports the Geometric Algebra of the Plane and
# the Geometric Algebra generated by a Euclidean 3D vector space.
#
# blade does not support graphics. For that you should use the eight module which contains an
# encapsulation of the powerful Three.js WebGL API with extensions for Geometric Algebra. The
# eight module also contains its own multivector that is more suited to graphics.
#
# Geometric Algebra of 2D Euclidean Space (the "Plane").
# ======================================================
#
# This algebra contains an even sub-algebra that is isomorphic to complex numbers.
#
# Geometric Algebra of 3D Euclidean Space.
# ========================================
#
# This algebra is isomorphic to the algebra generated by the Pauli matrices.
# The even sub-algebra is also isomorphic to Quaternions.

